@reservationId = 695f52bd-34e4-46ab-83c3-ed8832662aff
@parkingSpotId = 00000000-0000-0000-0000-000000000001
###

GET {{MySpot_HostAddress}}/reservations
Accept: application/json

###

GET {{MySpot_HostAddress}}/reservations/{{reservationId}}
Accept: application/json

###

POST {{MySpot_HostAddress}}/reservations/vehicle
Content-Type: application/json

{
    "employeeName": "John Doe",
    "parkingSpotId": "{{parkingSpotId}}",
    "licensePlate": "XYZ123",
    "date": "2026-02-18"
}

###

POST {{MySpot_HostAddress}}/reservations/cleaning
Content-Type: application/json

{
    "parkingSpotId": "{{parkingSpotId}}",
    "date": "2026-02-18"
}

###

PUT {{MySpot_HostAddress}}/reservations/{{reservationId}}
Content-Type: application/json

{
  "licensePlate": "Neeeew"
}

###

DELETE {{MySpot_HostAddress}}/reservations/{{reservationId}}

###

GET {{MySpot_HostAddress}}