@reservationId = cffd5bf6-10d4-4d71-8bf7-06705821f873
@parkingSpotId = 00000000-0000-0000-0000-000000000003
###

GET {{MySpot_HostAddress}}
Accept: application/json

###

POST {{MySpot_HostAddress}}/{{parkingSpotId}}/reservations/vehicle
Content-Type: application/json

{
    "employeeName": "John Doe",
    "parkingSpotId": "{{parkingSpotId}}",
    "licensePlate": "XYZ123",
    "date": "2026-02-19",
    "capacity": 1
}

###

POST {{MySpot_HostAddress}}/reservations/cleaning
Content-Type: application/json

{
    "parkingSpotId": "{{parkingSpotId}}",
    "date": "2026-02-19"
}

###

PUT {{MySpot_HostAddress}}/reservations/{{reservationId}}
Content-Type: application/json

{
  "licensePlate": "Neeeew"
}

###

DELETE {{MySpot_HostAddress}}/reservations/{{reservationId}}

###

GET {{MySpot_HostAddress}}