@reservationId = 8fda95ac-d18f-40b5-a025-59bff7ee9df9
@parkingSpotId = 00000000-0000-0000-0000-000000000001
###

GET {{MySpot_HostAddress}}/reservations
Accept: application/json

###

GET {{MySpot_HostAddress}}/reservations/{{reservationId}}
Accept: application/json

###

POST {{MySpot_HostAddress}}/reservations
Content-Type: application/json

{
    "employeeName": "John Doe",
    "parkingSpotId": "{{parkingSpotId}}",
    "licensePlate": "XYZ123",
    "date": "2026-02-11"
}

###

PUT {{MySpot_HostAddress}}/reservations/{{reservationId}}
Content-Type: application/json

{
  "licensePlate": "Neeeew"
}

###

DELETE {{MySpot_HostAddress}}/reservations/{{reservationId}}

###

GET {{MySpot_HostAddress}}